server:
  port: 10002


#服务名
spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
      routes:
      - id:  apiuser
        # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
        uri: lb://panyibuying-web
        predicates:
        # 重点！转发该路径！,/userapi/**,
        - Path=/api/**
        # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
        #而不是我们期望的去掉userapi，只保留**部分
        filters:
        - StripPrefix=1
      - id:  api2user
        uri: lb://asset-wallet-service
        predicates:
        - Path=/asset/**
        filters:
        - StripPrefix=1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/