spring:
  profiles:
    active: dev
  application:
    # 此名称将会作为服务的实例名
    name: yobtc-config-center
  output:
    ansi:
      enabled: always
---
# 开发环境配置
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: http://47.99.39.170/ProjectConfig/YOBTC-BDD-DEVELOP-CONFIG.git
          searchPaths: config
          username: DevConfig
          password: 0cIYZdhVjVPdiohtkeUW
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.112:8888/eureka/
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/yobtc-user-service/dev/master
    prefer-ip-address: true
server:
  port: 9888