server:
  port: 10003

spring:
  application:
    name: YOBTC-CONFIG-CENTER
  cloud:
    config:
      server:
        git:
#          uri: http://47.99.39.170/ProjectConfig/YOBTC-BDD-DEVELOP-CONFIG.git
          uri: https://github.com/zzh921221/demo.git
          search-paths: CONFIG/dev

  rabbitmq:
    host: 192.168.1.112
    port: 5672
    username: admin
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
      defaultZone: http://192.168.1.112:10001/eureka/
  instance:
    # \u5141\u8BB8\u663E\u793A\u670D\u52A1\u7684IP\u5730\u5740\uFF0Cfalse\uFF1A\u5219\u663E\u793A\u4E3B\u673A\u540D\u79F0
    prefer-ip-address: true
    # \u5B9E\u4F8B\u6807\u8BC6\uFF0C\u6D88\u8D39\u8005\u901A\u8FC7\u6CE8\u518C\u4E2D\u5FC3\u627E\u5230\u6B64\u5B9E\u4F8B\uFF1B\u5B9E\u4F8B\u4E3A\u5177\u4F53\u7684\u670D\u52A1
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    # \u8BBE\u7F6E\u72B6\u6001\u9875\uFF0C\u7528\u4E8E\u63D0\u4F9B\u6D88\u8D39\u8005\u67E5\u627E\u5177\u4F53\u7684\u670D\u52A1\u65B9\u6CD5
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html